report/io/ini_parser.py
tests/io/test_ini_parser.py

This function provides the functionality to return the content of the xml element attrib in the desired datatype and reports errors. It can also check if a provided condition is met (e.g., content >= 0, or content is a directory/file). Hence, it reduces some the function complexity overall.

Parsing of xml_attrib now in extra function

---

report/data/trajectory_data.py
report/io/trajectory_parser.py
report/methods/density_calculator.py
report/methods/method_utils.py
requirements.txt
tests/data/test_trajectory_data.py
tests/io/test_trajectory_parser.py
tests/methods/test_density_calculator.py
tests/methods/test_method_utils.py
tests/utils/utils.py

Add method to compute the classic density within a given measurement area.
Newly added library function:
```python
def compute_classic_density(
traj_data: TrajectoryData,
measurement_area: pygeos.Geometry,
) -> pd.DataFrame:
"""Compute the classic density of the trajectory per frame inside the given measurement area
Args:
traj_data (TrajectoryData): trajectory data to analyze
measurement_area (pygeos.Geometry): area for which the density is computed
Returns:
DataFrame containing the columns: 'frame' and 'density'
"""
```
Can be used as:
```python
from report.methods.density_calculator import compute_classic_density
df_density = compute_classic_density(trajectory_data, measurement_area)
```
Closes #24

Compute classic density

---

report/methods/density_calculator.py
usage.ipynb

Ensures that the voronoi cells do not get larger than the specified cut-off radius. They will be intersected with a circle with that radius.

Add possibility to cut-off the voronoi cells at a radius

---

analyzer/methods/flow_calculator.py
analyzer/methods/method_utils.py
usage.ipynb

Fix bug in frame range computation

---

analyzer/io/trajectory_parser.py
tests/reference_tests/reference_test.py
tests/unit_tests/io/test_trajectory_parser.py
usage.ipynb

This can be used to parse files, where the frame rate is not provided in the trajectory file

Pass default frame rate to trajectory parser

---

.github/workflows/ci.yml

Upload commits to test-pypi

---

analyzer/methods/density_calculator.py
usage.ipynb

Make tuple from cut-off parameters of voronoi density

---

analyzer/methods/profile_calculator.py

Fix future warning in profile computation

---

analyzer/__init__.py
analyzer/data/trajectory_data.py
analyzer/io/trajectory_parser.py
tests/reference_tests/reference_test.py
tests/unit_tests/io/test_trajectory_parser.py
tests/utils/utils.py
usage.ipynb

- remove not needed functions
- make some functions private
- use same behavior for frame rate and units
- rename to load instead of parse
- parsing of meta data now in one single function instead of 2

Clean up trajectory parser

---

analyzer/io/trajectory_parser.py
tests/unit_tests/io/test_trajectory_parser.py
usage.ipynb

Add checks if trajectory file does exist and is a file.

---

analyzer/methods/method_utils.py

Add check if min_frame <= max_frame

---

.github/workflows/ci.yml
analyzer/data/geometry.py
analyzer/data/trajectory_data.py
analyzer/methods/density_calculator.py
analyzer/methods/flow_calculator.py
analyzer/methods/method_utils.py
analyzer/methods/profile_calculator.py
analyzer/methods/velocity_calculator.py
requirements.txt
setup.py
tests/reference_tests/reference_test.py
tests/unit_tests/methods/test_density_calculator.py
tests/unit_tests/methods/test_method_utils.py
tests/utils/utils.py
usage.ipynb

Use Shapely instead of pygeos for geometric operations

---

pedpy/methods/flow_calculator.py
pedpy/methods/method_utils.py
requirements.txt
setup.py

Fix depreaction warning

---

CITATION.cff
README.md

Add citation cff

---

.github/workflows/ci.yml
pedpy/__init__.py
pedpy/data/geometry.py
pedpy/data/trajectory_data.py
pedpy/io/trajectory_loader.py
pedpy/methods/density_calculator.py
pedpy/methods/flow_calculator.py
pedpy/methods/method_utils.py
pedpy/methods/profile_calculator.py
pedpy/methods/velocity_calculator.py
pedpy/plotting/plotting.py
pyproject.toml
requirements.txt
setup.py

Fixup the docstrings to match the google docstring style. Also adds an CI test to ensure, that these are always well styled.

Fixup docstrings

---

requirements.txt
setup.py

After Shapely 2.0 is finally released, we update to use the final release.

Update to Shapely 2.0

---

pedpy/__init__.py
pedpy/methods/method_utils.py
usage.ipynb

Add method to compute the neighbors of the pedestrians

---

pedpy/methods/velocity_calculator.py
usage.ipynb

Allow computation of x and y components of the velocity

---

pedpy/methods/method_utils.py
tests/reference_tests/reference_test.py

- use blind points in every calculation
- use blind points ON now default
- warn if a frame is skipped when too few peds are in frame
Closes #160

Use blind points in every calculation (avoids some boundary effects)

---

pedpy/data/trajectory_data.py
pedpy/methods/density_calculator.py
pedpy/methods/flow_calculator.py
pedpy/methods/method_utils.py
pedpy/methods/profile_calculator.py
pedpy/methods/velocity_calculator.py
tests/reference_tests/reference_test.py
tests/utils/utils.py

Use only keyword arguments in all functions

---

docs/source/conf.py
notebooks/usage.ipynb
pedpy/__init__.py
pedpy/methods/flow_calculator.py
pedpy/methods/method_utils.py

Add distance/time to line computation

---

pedpy/methods/method_utils.py

Fix future warnings from Pandas

---

pedpy/plotting/plotting.py

Use correct automatic determinated vmin and vmax when plotting profiles

---

pedpy/methods/profile_calculator.py

Add Gaussian density profile calculation

---

.github/workflows/ci.yml
docs/requirements.txt
pedpy/io/trajectory_loader.py
requirements.txt
setup.py

Run CI on MacOS ARM

---

pedpy/data/geometry.py
tests/unit_tests/data/test_geometry.py

Support GeometryCollection as input type for geometries

---

docs/source/conf.py
notebooks/user_guide.ipynb
pedpy/methods/profile_calculator.py
pedpy/plotting/plotting.py

Add mean speed profile computation

---

pedpy/plotting/plotting.py

Use correct escape depending in plot label

---

notebooks/user_guide.ipynb
pedpy/data/trajectory_data.py

- allow slicing by frame
- all values displayed in __repr__ are now also accessible for users, e.g., bounds, number pedestrians, frame range
Closes #289

Improve TrajectoryData

---

.readthedocs.yaml
docs/source/demo-data
docs/source/fundamental_diagram.ipynb
docs/source/getting_started.ipynb
docs/source/user_guide.ipynb

Use links to the notebooks instead of copying them

---

docs/source/api/column_identifiers.rst
docs/source/api/index.rst
notebooks/user_guide.ipynb

Explain column identifiers

---

pyproject.toml

Add default-tag for shallow clone

---

notebooks/user_guide.ipynb
pedpy/plotting/plotting.py

Add speed colors to time distance plots

---

pedpy/plotting/plotting.py

The new function now plots the polygons correctly, meaning no longer overlapping of the fill color and the lines for narrow line widths. This will also remove the error of gaps in the boundary at the closing point of the polygons.

Add function to plot polygons

---

docs/source/changelog.rst

Adds the changelog summary for the bug-fix release 1.1.1
Waiting for #353 
When merged 1.1.1 can be released.

Add Changelog for 1.1.1

---

notebooks/user_guide.ipynb
pedpy/__init__.py
pedpy/methods/spatial_analysis.py

Fix naming of compute_pair_distribution_function

---

docs/source/changelog.rst

Automatic changelog (generated by GitHub):
* Check the return of the single tests by @schroedtert in https://github.com/PedestrianDynamics/PedPy/pull/311
* Run CI on rls-branches by @schroedtert in https://github.com/PedestrianDynamics/PedPy/pull/313
* Set default tag for versioningit by @schroedtert in https://github.com/PedestrianDynamics/PedPy/pull/316
* Update documentation by @schroedtert in https://github.com/PedestrianDynamics/PedPy/pull/315
* Intuitive Gaussian Density Calculation with FWHM Input by @chraibi in https://github.com/PedestrianDynamics/PedPy/pull/305
* Fix formatting by @schroedtert in https://github.com/PedestrianDynamics/PedPy/pull/319
* Improve developer guide by @schroedtert in https://github.com/PedestrianDynamics/PedPy/pull/317
* Fix used MacOS Version in CI by …

Update changelog for 1.2.0

---

.github/workflows/ci.yml
README.md
pyproject.toml

Support Python 3.11, 3.12, and 3.13

---

.gitignore
codecov.yml

- set a more relaxed threshold
- ignore plotting, as we won't test it

Improve codecov settings

---

pyproject.toml
requirements.txt

Add more flexible dependency management

---

pedpy/methods/method_utils.py

Fix Pandas deprecation warning

---

pedpy/__init__.py
pedpy/data/geometry.py
pedpy/data/trajectory_data.py
pedpy/errors.py
pedpy/io/trajectory_loader.py
pedpy/methods/acceleration_calculator.py
pedpy/methods/density_calculator.py
pedpy/methods/flow_calculator.py
pedpy/methods/method_utils.py
pedpy/methods/profile_calculator.py
pedpy/methods/speed_calculator.py
pedpy/plotting/plotting.py
tests/unit_tests/data/test_geometry.py
tests/unit_tests/methods/test_density_calculator.py
tests/unit_tests/methods/test_flow_calculator.py
tests/unit_tests/methods/test_speed_calculator.py

Introduce PedPy errors

---

.gitignore
pedpy/methods/acceleration_calculator.py
pedpy/methods/density_calculator.py
pedpy/methods/flow_calculator.py
pedpy/methods/method_utils.py
pedpy/methods/profile_calculator.py
pedpy/methods/spatial_analysis.py
pedpy/methods/speed_calculator.py

- Add explanation of columns in returned data frames
- Fix formatting of docstring for proper display on website
- Fix wrong column name in return of compute_individual_voronoi_polygons
Closes #463

Fix minor documentation issues
